default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  username: masa331
  password: plmkil5
  pool: 5

development:
  <<: *default
  database: basset_scan_development

test:
  <<: *default
  database: basset_scan_test

production:
  <<: *default
  database: basset_watch_production
  username: basset_watch
  password: <%= ENV['BASSET_WATCH_DATABASE_PASSWORD'] %>
